// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Analizadores/Lexico.jflex

package Analizadores;

//importaciones
import java_cup.runtime.Symbol;
import java.util.LinkedList;
import Errores.Errores;


@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  1,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  0,  0,  6,  7,  8,  9, 10, 11, 12,  0, 13, 14, 15, 
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 18, 19, 20, 21,  0, 
     0, 22, 23, 24, 25, 26, 27, 28, 29, 30,  0, 31, 32, 33, 34, 35, 
    36,  0, 37, 38, 39, 40, 41, 42,  0,  0,  0,  0,  0,  0, 43, 44, 
     0, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 
    60, 54, 61, 62, 63, 64, 65, 66, 54, 54, 54, 67, 68, 69,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\20\1\1\21\21\22\1\23\1\1"+
    "\1\24\1\0\1\25\10\0\1\26\4\0\1\27\16\0"+
    "\5\22\1\26\4\22\1\27\16\22\1\30\1\31\1\32"+
    "\1\33\11\0\1\34\1\35\3\0\1\36\10\0\1\37"+
    "\2\0\11\22\1\34\1\35\3\22\1\36\10\22\1\37"+
    "\2\22\1\0\1\40\1\0\1\41\3\0\1\42\1\0"+
    "\1\43\1\0\1\44\11\0\1\45\1\46\1\0\1\22"+
    "\1\40\1\22\1\41\3\22\1\42\1\22\1\43\1\22"+
    "\1\44\11\22\1\45\1\46\1\22\1\0\1\47\1\50"+
    "\2\0\1\51\1\0\1\52\3\0\1\53\4\0\1\54"+
    "\1\22\1\47\1\50\2\22\1\51\1\22\1\52\3\22"+
    "\1\53\4\22\1\54\1\55\1\0\1\56\1\57\1\0"+
    "\1\60\1\61\1\0\1\62\1\63\1\0\1\55\1\22"+
    "\1\56\1\57\1\22\1\60\1\61\1\22\1\62\1\63"+
    "\1\22\1\0\1\64\2\0\1\22\1\64\2\22\1\65"+
    "\1\0\1\66\1\65\1\22\1\66\1\0\1\22\2\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[290];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\106\0\322\0\106\0\u0118\0\u015e"+
    "\0\106\0\106\0\106\0\u01a4\0\u01ea\0\106\0\u0230\0\106"+
    "\0\106\0\106\0\106\0\106\0\u0276\0\u02bc\0\u0302\0\u0348"+
    "\0\u038e\0\u03d4\0\u041a\0\u0460\0\u04a6\0\u04ec\0\u0532\0\u0578"+
    "\0\u05be\0\u0604\0\u064a\0\u0690\0\106\0\u06d6\0\u071c\0\u0762"+
    "\0\u07a8\0\u07ee\0\u0834\0\u087a\0\u08c0\0\u0906\0\u094c\0\u0992"+
    "\0\u09d8\0\u0a1e\0\u0a64\0\u0aaa\0\u0af0\0\u0b36\0\106\0\u0b7c"+
    "\0\106\0\u0bc2\0\106\0\u0c08\0\u0c4e\0\u0c94\0\u0cda\0\u0d20"+
    "\0\u0d66\0\u0dac\0\u0df2\0\u0e38\0\u0e7e\0\u0ec4\0\u0f0a\0\u0f50"+
    "\0\106\0\u0f96\0\u0fdc\0\u1022\0\u1068\0\u10ae\0\u10f4\0\u113a"+
    "\0\u1180\0\u11c6\0\u120c\0\u1252\0\u1298\0\u12de\0\u1324\0\u136a"+
    "\0\u13b0\0\u13f6\0\u143c\0\u1482\0\u14c8\0\u150e\0\u1554\0\u159a"+
    "\0\u15e0\0\u087a\0\u1626\0\u166c\0\u16b2\0\u16f8\0\u173e\0\u1784"+
    "\0\u17ca\0\u1810\0\u1856\0\u189c\0\u18e2\0\u1928\0\u196e\0\u19b4"+
    "\0\106\0\106\0\106\0\u0c94\0\u19fa\0\u1a40\0\u1a86\0\u1acc"+
    "\0\u1b12\0\u1b58\0\u1b9e\0\u1be4\0\u1c2a\0\106\0\106\0\u1c70"+
    "\0\u1cb6\0\u1cfc\0\106\0\u1d42\0\u1d88\0\u1dce\0\u1e14\0\u1e5a"+
    "\0\u1ea0\0\u1ee6\0\u1f2c\0\106\0\u1f72\0\u1fb8\0\u1ffe\0\u2044"+
    "\0\u208a\0\u20d0\0\u2116\0\u215c\0\u21a2\0\u21e8\0\u222e\0\u087a"+
    "\0\u087a\0\u2274\0\u22ba\0\u2300\0\u087a\0\u2346\0\u238c\0\u23d2"+
    "\0\u2418\0\u245e\0\u24a4\0\u24ea\0\u2530\0\u087a\0\u2576\0\u25bc"+
    "\0\u2602\0\106\0\u2648\0\106\0\u268e\0\u26d4\0\u271a\0\106"+
    "\0\u2760\0\106\0\u27a6\0\106\0\u27ec\0\u2832\0\u2878\0\u28be"+
    "\0\u2904\0\u294a\0\u2990\0\u29d6\0\u2a1c\0\106\0\106\0\u2a62"+
    "\0\u2aa8\0\u087a\0\u2aee\0\u087a\0\u2b34\0\u2b7a\0\u2bc0\0\u087a"+
    "\0\u2c06\0\u087a\0\u2c4c\0\u087a\0\u2c92\0\u2cd8\0\u2d1e\0\u2d64"+
    "\0\u2daa\0\u2df0\0\u2e36\0\u2e7c\0\u2ec2\0\u087a\0\u087a\0\u2f08"+
    "\0\u2f4e\0\106\0\106\0\u2f94\0\u2fda\0\106\0\u3020\0\106"+
    "\0\u3066\0\u30ac\0\u30f2\0\106\0\u3138\0\u317e\0\u31c4\0\u320a"+
    "\0\106\0\u3250\0\u087a\0\u087a\0\u3296\0\u32dc\0\u087a\0\u3322"+
    "\0\u087a\0\u3368\0\u33ae\0\u33f4\0\u087a\0\u343a\0\u3480\0\u34c6"+
    "\0\u350c\0\u087a\0\106\0\u3552\0\106\0\106\0\u3598\0\106"+
    "\0\106\0\u35de\0\106\0\106\0\u3624\0\u087a\0\u366a\0\u087a"+
    "\0\u087a\0\u36b0\0\u087a\0\u087a\0\u36f6\0\u087a\0\u087a\0\u373c"+
    "\0\u3782\0\106\0\u37c8\0\u380e\0\u3854\0\u087a\0\u389a\0\u38e0"+
    "\0\106\0\u3926\0\106\0\u087a\0\u396c\0\u087a\0\u39b2\0\u39f8"+
    "\0\106\0\u087a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[290];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\2\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\2\2\1\33\1\2\1\34\1\35"+
    "\1\36\1\2\1\37\1\40\1\41\1\42\1\2\1\43"+
    "\1\44\1\45\1\2\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\2\54\1\55\2\54\1\56\1\57\1\60\1\54"+
    "\1\61\1\62\1\63\1\64\1\54\1\65\1\66\1\67"+
    "\1\70\1\71\107\0\2\3\103\0\2\72\1\0\2\72"+
    "\1\0\100\72\7\0\1\73\76\0\2\74\1\0\5\74"+
    "\1\0\75\74\20\0\1\75\105\0\1\17\103\0\1\76"+
    "\1\0\1\17\131\0\1\77\27\0\1\77\54\0\1\100"+
    "\1\0\1\101\25\0\1\100\1\0\1\101\45\0\1\102"+
    "\5\0\1\103\20\0\1\102\6\0\1\103\55\0\1\104"+
    "\27\0\1\104\52\0\1\105\27\0\1\105\43\0\1\106"+
    "\7\0\1\107\4\0\1\110\11\0\1\106\7\0\1\107"+
    "\5\0\1\110\45\0\1\111\6\0\1\112\17\0\1\111"+
    "\7\0\1\112\45\0\1\113\3\0\1\114\22\0\1\113"+
    "\3\0\1\114\46\0\1\115\26\0\1\115\62\0\1\116"+
    "\26\0\1\116\71\0\1\117\27\0\1\117\42\0\1\120"+
    "\10\0\1\121\15\0\1\120\11\0\1\121\61\0\1\122"+
    "\27\0\1\122\51\0\1\123\1\0\1\124\25\0\1\123"+
    "\1\0\1\124\36\0\1\125\14\0\1\126\11\0\1\125"+
    "\15\0\1\126\47\0\1\127\26\0\1\127\41\0\1\54"+
    "\23\0\1\77\7\0\20\54\1\130\6\54\23\0\1\54"+
    "\22\0\1\100\1\0\1\101\6\0\17\54\1\131\1\54"+
    "\1\132\5\54\23\0\1\54\14\0\1\102\5\0\1\103"+
    "\10\0\10\54\1\133\6\54\1\134\7\54\23\0\1\54"+
    "\22\0\1\104\10\0\17\54\1\135\7\54\23\0\1\54"+
    "\17\0\1\105\13\0\14\54\1\136\12\54\23\0\1\54"+
    "\5\0\1\106\7\0\1\107\4\0\1\110\10\0\1\54"+
    "\1\137\7\54\1\140\5\54\1\141\7\54\23\0\1\54"+
    "\33\0\27\54\23\0\1\54\12\0\1\111\6\0\1\112"+
    "\11\0\6\54\1\142\7\54\1\143\10\54\23\0\1\54"+
    "\11\0\1\113\3\0\1\114\15\0\5\54\1\144\3\54"+
    "\1\145\15\54\23\0\1\54\5\0\1\115\25\0\1\54"+
    "\1\146\25\54\23\0\1\54\11\0\1\116\21\0\5\54"+
    "\1\147\21\54\23\0\1\54\24\0\1\117\6\0\21\54"+
    "\1\150\5\54\23\0\1\54\11\0\1\120\10\0\1\121"+
    "\10\0\5\54\1\151\11\54\1\152\7\54\23\0\1\54"+
    "\26\0\1\122\4\0\23\54\1\153\3\54\23\0\1\54"+
    "\22\0\1\123\1\0\1\124\6\0\17\54\1\154\1\54"+
    "\1\155\5\54\23\0\1\54\5\0\1\125\14\0\1\126"+
    "\10\0\1\54\1\156\15\54\1\157\7\54\23\0\1\54"+
    "\14\0\1\127\16\0\10\54\1\160\16\54\107\0\1\161"+
    "\1\0\2\72\1\0\2\72\1\162\100\72\2\74\1\0"+
    "\5\74\1\163\75\74\16\0\1\76\1\0\1\75\105\0"+
    "\1\164\131\0\1\165\27\0\1\165\54\0\1\166\27\0"+
    "\1\166\44\0\1\167\26\0\1\167\52\0\1\170\26\0"+
    "\1\170\72\0\1\171\27\0\1\171\63\0\1\172\27\0"+
    "\1\172\53\0\1\173\27\0\1\173\47\0\1\174\27\0"+
    "\1\174\57\0\1\175\27\0\1\175\60\0\1\176\27\0"+
    "\1\176\57\0\1\177\27\0\1\177\50\0\1\200\27\0"+
    "\1\200\61\0\1\201\27\0\1\201\56\0\1\202\27\0"+
    "\1\202\60\0\1\203\27\0\1\203\41\0\1\204\26\0"+
    "\1\204\61\0\1\205\5\0\1\206\21\0\1\205\5\0"+
    "\1\206\56\0\1\207\27\0\1\207\33\0\1\210\16\0"+
    "\1\211\7\0\1\210\17\0\1\211\56\0\1\212\27\0"+
    "\1\212\57\0\1\213\27\0\1\213\52\0\1\214\27\0"+
    "\1\214\46\0\1\215\26\0\1\215\56\0\1\216\26\0"+
    "\1\216\40\0\1\54\23\0\1\165\7\0\20\54\1\217"+
    "\6\54\23\0\1\54\22\0\1\166\10\0\17\54\1\220"+
    "\7\54\23\0\1\54\11\0\1\167\21\0\5\54\1\221"+
    "\21\54\23\0\1\54\5\0\1\170\25\0\1\54\1\222"+
    "\25\54\23\0\1\54\21\0\1\171\11\0\16\54\1\223"+
    "\10\54\23\0\1\54\27\0\1\172\3\0\24\54\1\224"+
    "\2\54\23\0\1\54\25\0\1\173\5\0\22\54\1\225"+
    "\4\54\23\0\1\54\17\0\1\174\13\0\14\54\1\226"+
    "\12\54\23\0\1\54\21\0\1\175\11\0\16\54\1\227"+
    "\10\54\23\0\1\54\24\0\1\176\6\0\21\54\1\230"+
    "\5\54\23\0\1\54\26\0\1\177\4\0\23\54\1\231"+
    "\3\54\23\0\1\54\21\0\1\200\11\0\16\54\1\232"+
    "\10\54\23\0\1\54\25\0\1\201\5\0\22\54\1\233"+
    "\4\54\23\0\1\54\26\0\1\202\4\0\23\54\1\234"+
    "\3\54\23\0\1\54\31\0\1\203\1\0\26\54\1\235"+
    "\23\0\1\54\15\0\1\204\15\0\11\54\1\236\15\54"+
    "\23\0\1\54\20\0\1\205\5\0\1\206\4\0\15\54"+
    "\1\237\5\54\1\240\3\54\23\0\1\54\27\0\1\207"+
    "\3\0\24\54\1\241\2\54\23\0\1\54\5\0\1\210"+
    "\16\0\1\211\6\0\1\54\1\242\17\54\1\243\5\54"+
    "\23\0\1\54\25\0\1\212\5\0\22\54\1\244\4\54"+
    "\23\0\1\54\27\0\1\213\3\0\24\54\1\245\2\54"+
    "\23\0\1\54\24\0\1\214\6\0\21\54\1\246\5\54"+
    "\23\0\1\54\15\0\1\215\15\0\11\54\1\247\15\54"+
    "\23\0\1\54\15\0\1\216\15\0\11\54\1\250\15\54"+
    "\35\0\1\251\26\0\1\251\64\0\1\252\27\0\1\252"+
    "\43\0\1\253\26\0\1\253\75\0\1\254\27\0\1\254"+
    "\56\0\1\255\1\256\26\0\1\255\1\256\35\0\1\257"+
    "\26\0\1\257\61\0\1\260\26\0\1\260\72\0\1\261"+
    "\27\0\1\261\40\0\1\262\26\0\1\262\61\0\1\263"+
    "\26\0\1\263\71\0\1\264\27\0\1\264\36\0\1\265"+
    "\26\0\1\265\70\0\1\266\27\0\1\266\56\0\1\267"+
    "\27\0\1\267\62\0\1\270\27\0\1\270\47\0\1\271"+
    "\27\0\1\271\60\0\1\272\27\0\1\272\46\0\1\273"+
    "\11\0\1\274\14\0\1\273\12\0\1\274\54\0\1\275"+
    "\27\0\1\275\40\0\1\276\26\0\1\276\55\0\1\277"+
    "\26\0\1\277\65\0\1\300\27\0\1\300\35\0\1\54"+
    "\11\0\1\251\21\0\5\54\1\301\21\54\23\0\1\54"+
    "\17\0\1\252\13\0\14\54\1\302\12\54\23\0\1\54"+
    "\5\0\1\253\25\0\1\54\1\303\25\54\23\0\1\54"+
    "\24\0\1\254\6\0\21\54\1\304\5\54\23\0\1\54"+
    "\25\0\1\255\1\256\4\0\22\54\1\305\1\306\3\54"+
    "\23\0\1\54\6\0\1\257\24\0\2\54\1\307\24\54"+
    "\23\0\1\54\11\0\1\260\21\0\5\54\1\310\21\54"+
    "\23\0\1\54\25\0\1\261\5\0\22\54\1\311\4\54"+
    "\23\0\1\54\10\0\1\262\22\0\4\54\1\312\22\54"+
    "\23\0\1\54\13\0\1\263\17\0\7\54\1\313\17\54"+
    "\23\0\1\54\26\0\1\264\4\0\23\54\1\314\3\54"+
    "\23\0\1\54\7\0\1\265\23\0\3\54\1\315\23\54"+
    "\23\0\1\54\21\0\1\266\11\0\16\54\1\316\10\54"+
    "\23\0\1\54\22\0\1\267\10\0\17\54\1\317\7\54"+
    "\23\0\1\54\27\0\1\270\3\0\24\54\1\320\2\54"+
    "\23\0\1\54\21\0\1\271\11\0\16\54\1\321\10\54"+
    "\23\0\1\54\24\0\1\272\6\0\21\54\1\322\5\54"+
    "\23\0\1\54\15\0\1\273\11\0\1\274\3\0\11\54"+
    "\1\323\12\54\1\324\2\54\23\0\1\54\26\0\1\275"+
    "\4\0\23\54\1\325\3\54\23\0\1\54\11\0\1\276"+
    "\21\0\5\54\1\326\21\54\23\0\1\54\10\0\1\277"+
    "\22\0\4\54\1\327\22\54\23\0\1\54\17\0\1\300"+
    "\13\0\14\54\1\330\12\54\45\0\1\331\27\0\1\331"+
    "\52\0\1\332\27\0\1\332\65\0\1\333\27\0\1\333"+
    "\44\0\1\334\26\0\1\334\60\0\1\335\27\0\1\335"+
    "\47\0\1\336\26\0\1\336\73\0\1\337\27\0\1\337"+
    "\43\0\1\340\26\0\1\340\70\0\1\341\27\0\1\341"+
    "\57\0\1\342\27\0\1\342\51\0\1\343\27\0\1\343"+
    "\41\0\1\344\26\0\1\344\74\0\1\345\27\0\1\345"+
    "\50\0\1\346\27\0\1\346\43\0\1\347\26\0\1\347"+
    "\73\0\1\350\27\0\1\350\42\0\1\351\26\0\1\351"+
    "\44\0\1\54\21\0\1\331\11\0\16\54\1\352\10\54"+
    "\23\0\1\54\16\0\1\332\14\0\13\54\1\353\13\54"+
    "\23\0\1\54\26\0\1\333\4\0\23\54\1\354\3\54"+
    "\23\0\1\54\15\0\1\334\15\0\11\54\1\355\15\54"+
    "\23\0\1\54\17\0\1\335\13\0\14\54\1\356\12\54"+
    "\23\0\1\54\11\0\1\336\21\0\5\54\1\357\21\54"+
    "\23\0\1\54\26\0\1\337\4\0\23\54\1\360\3\54"+
    "\23\0\1\54\14\0\1\340\16\0\10\54\1\361\16\54"+
    "\23\0\1\54\26\0\1\341\4\0\23\54\1\362\3\54"+
    "\23\0\1\54\30\0\1\342\2\0\25\54\1\363\1\54"+
    "\23\0\1\54\24\0\1\343\6\0\21\54\1\364\5\54"+
    "\23\0\1\54\10\0\1\344\22\0\4\54\1\365\22\54"+
    "\23\0\1\54\26\0\1\345\4\0\23\54\1\366\3\54"+
    "\23\0\1\54\21\0\1\346\11\0\16\54\1\367\10\54"+
    "\23\0\1\54\7\0\1\347\23\0\3\54\1\370\23\54"+
    "\23\0\1\54\24\0\1\350\6\0\21\54\1\371\5\54"+
    "\23\0\1\54\11\0\1\351\21\0\5\54\1\372\21\54"+
    "\34\0\1\373\26\0\1\373\67\0\1\374\27\0\1\374"+
    "\45\0\1\375\26\0\1\375\61\0\1\376\26\0\1\376"+
    "\61\0\1\377\27\0\1\377\47\0\1\u0100\26\0\1\u0100"+
    "\66\0\1\u0101\27\0\1\u0101\67\0\1\u0102\65\0\1\u0103"+
    "\26\0\1\u0103\71\0\1\u0104\27\0\1\u0104\44\0\1\u0105"+
    "\26\0\1\u0105\40\0\1\54\10\0\1\373\22\0\4\54"+
    "\1\u0106\22\54\23\0\1\54\21\0\1\374\11\0\16\54"+
    "\1\u0107\10\54\23\0\1\54\11\0\1\375\21\0\5\54"+
    "\1\u0108\21\54\23\0\1\54\14\0\1\376\16\0\10\54"+
    "\1\u0109\16\54\23\0\1\54\17\0\1\377\13\0\14\54"+
    "\1\u010a\12\54\23\0\1\54\11\0\1\u0100\21\0\5\54"+
    "\1\u010b\21\54\23\0\1\54\21\0\1\u0101\11\0\16\54"+
    "\1\u010c\10\54\23\0\1\54\33\0\1\u010d\26\54\23\0"+
    "\1\54\13\0\1\u0103\17\0\7\54\1\u010e\17\54\23\0"+
    "\1\54\26\0\1\u0104\4\0\23\54\1\u010f\3\54\23\0"+
    "\1\54\15\0\1\u0105\15\0\11\54\1\u0110\15\54\53\0"+
    "\1\u0111\27\0\1\u0111\47\0\1\u0112\27\0\1\u0112\65\0"+
    "\1\u0113\27\0\1\u0113\45\0\1\u0114\27\0\1\u0114\33\0"+
    "\1\54\27\0\1\u0111\3\0\24\54\1\u0115\2\54\23\0"+
    "\1\54\21\0\1\u0112\11\0\16\54\1\u0116\10\54\23\0"+
    "\1\54\31\0\1\u0113\1\0\26\54\1\u0117\23\0\1\54"+
    "\21\0\1\u0114\11\0\16\54\1\u0118\10\54\35\0\1\u0119"+
    "\26\0\1\u0119\62\0\1\u011a\26\0\1\u011a\54\0\1\u011b"+
    "\26\0\1\u011b\42\0\1\54\11\0\1\u0119\21\0\5\54"+
    "\1\u011c\21\54\23\0\1\54\15\0\1\u011a\15\0\11\54"+
    "\1\u011d\15\54\23\0\1\54\13\0\1\u011b\17\0\7\54"+
    "\1\u011e\17\54\52\0\1\u011f\27\0\1\u011f\26\0\1\54"+
    "\26\0\1\u011f\4\0\23\54\1\u0120\3\54\40\0\1\u0121"+
    "\26\0\1\u0121\41\0\1\54\14\0\1\u0121\16\0\10\54"+
    "\1\u0122\16\54\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[14910];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\2\1\3\11"+
    "\2\1\1\11\1\1\5\11\20\1\1\11\21\1\1\11"+
    "\1\1\1\11\1\0\1\11\10\0\1\1\4\0\1\11"+
    "\16\0\31\1\3\11\1\1\11\0\2\11\3\0\1\11"+
    "\10\0\1\11\2\0\32\1\1\0\1\11\1\0\1\11"+
    "\3\0\1\11\1\0\1\11\1\0\1\11\11\0\2\11"+
    "\1\0\30\1\1\0\2\11\2\0\1\11\1\0\1\11"+
    "\3\0\1\11\4\0\1\11\21\1\1\11\1\0\2\11"+
    "\1\0\2\11\1\0\2\11\1\0\13\1\1\0\1\11"+
    "\2\0\4\1\1\11\1\0\1\11\3\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[290];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public LinkedList<Errores> listaErrores = new LinkedList<>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    listaErrores = new LinkedList<>();
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { listaErrores.add(new Errores("LEXICO","El caracter "+
                yytext()+" NO pertenece al lenguaje", yyline, yycolumn));
                System.out.println(yytext());
            }
          // fall through
          case 56: break;
          case 2:
            { 
            }
          // fall through
          case 57: break;
          case 3:
            { return new Symbol(sym.SYMNOT, yyline, yycolumn,yytext());
            }
          // fall through
          case 58: break;
          case 4:
            { return new Symbol(sym.Porcentaje, yyline, yycolumn,yytext());
            }
          // fall through
          case 59: break;
          case 5:
            { return new Symbol(sym.AbreP, yyline, yycolumn,yytext());
            }
          // fall through
          case 60: break;
          case 6:
            { return new Symbol(sym.CierraP, yyline, yycolumn,yytext());
            }
          // fall through
          case 61: break;
          case 7:
            { return new Symbol(sym.Asterisco, yyline, yycolumn,yytext());
            }
          // fall through
          case 62: break;
          case 8:
            { return new Symbol(sym.Suma, yyline, yycolumn,yytext());
            }
          // fall through
          case 63: break;
          case 9:
            { return new Symbol(sym.Resta, yyline, yycolumn,yytext());
            }
          // fall through
          case 64: break;
          case 10:
            { return new Symbol(sym.Diagonal, yyline, yycolumn,yytext());
            }
          // fall through
          case 65: break;
          case 11:
            { return new Symbol(sym.entero, yyline, yycolumn,yytext());
            }
          // fall through
          case 66: break;
          case 12:
            { return new Symbol(sym.DosPuntos, yyline, yycolumn,yytext());
            }
          // fall through
          case 67: break;
          case 13:
            { return new Symbol(sym.PuntoComa, yyline, yycolumn,yytext());
            }
          // fall through
          case 68: break;
          case 14:
            { return new Symbol(sym.menor, yyline, yycolumn,yytext());
            }
          // fall through
          case 69: break;
          case 15:
            { return new Symbol(sym.Igual, yyline, yycolumn,yytext());
            }
          // fall through
          case 70: break;
          case 16:
            { return new Symbol(sym.mayor, yyline, yycolumn,yytext());
            }
          // fall through
          case 71: break;
          case 17:
            { return new Symbol(sym.acentoPotencia, yyline, yycolumn,yytext());
            }
          // fall through
          case 72: break;
          case 18:
            { return new Symbol(sym.ident, yyline, yycolumn,yytext());
            }
          // fall through
          case 73: break;
          case 19:
            { return new Symbol(sym.AbreC, yyline, yycolumn,yytext());
            }
          // fall through
          case 74: break;
          case 20:
            { return new Symbol(sym.CierraC, yyline, yycolumn,yytext());
            }
          // fall through
          case 75: break;
          case 21:
            { return new Symbol(sym.SYMAND, yyline, yycolumn,yytext());
            }
          // fall through
          case 76: break;
          case 22:
            { return new Symbol(sym.PRdo, yyline, yycolumn,yytext());
            }
          // fall through
          case 77: break;
          case 23:
            { return new Symbol(sym.PRif, yyline, yycolumn,yytext());
            }
          // fall through
          case 78: break;
          case 24:
            { return new Symbol(sym.SYMOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 79: break;
          case 25:
            { String cadena = yytext();
    cadena = cadena.substring(1, cadena.length()-1);
    return new Symbol(sym.cadena, yyline, yycolumn,cadena);
            }
          // fall through
          case 80: break;
          case 26:
            { return new Symbol(sym.character, yyline, yycolumn,yytext());
            }
          // fall through
          case 81: break;
          case 27:
            { return new Symbol(sym.doublee, yyline, yycolumn,yytext());
            }
          // fall through
          case 82: break;
          case 28:
            { return new Symbol(sym.PRfor, yyline, yycolumn,yytext());
            }
          // fall through
          case 83: break;
          case 29:
            { return new Symbol(sym.PRint, yyline, yycolumn,yytext());
            }
          // fall through
          case 84: break;
          case 30:
            { return new Symbol(sym.PRnew, yyline, yycolumn,yytext());
            }
          // fall through
          case 85: break;
          case 31:
            { return new Symbol(sym.PRvar, yyline, yycolumn,yytext());
            }
          // fall through
          case 86: break;
          case 32:
            { return new Symbol(sym.PRbool, yyline, yycolumn,yytext());
            }
          // fall through
          case 87: break;
          case 33:
            { return new Symbol(sym.PRchar, yyline, yycolumn,yytext());
            }
          // fall through
          case 88: break;
          case 34:
            { return new Symbol(sym.PRelse, yyline, yycolumn,yytext());
            }
          // fall through
          case 89: break;
          case 35:
            { return new Symbol(sym.PRfind, yyline, yycolumn,yytext());
            }
          // fall through
          case 90: break;
          case 36:
            { return new Symbol(sym.PRlist, yyline, yycolumn,yytext());
            }
          // fall through
          case 91: break;
          case 37:
            { return new Symbol(sym.PRtrue, yyline, yycolumn,yytext());
            }
          // fall through
          case 92: break;
          case 38:
            { return new Symbol(sym.PRvoid, yyline, yycolumn,yytext());
            }
          // fall through
          case 93: break;
          case 39:
            { return new Symbol(sym.PRbreak, yyline, yycolumn,yytext());
            }
          // fall through
          case 94: break;
          case 40:
            { return new Symbol(sym.PRconst, yyline, yycolumn,yytext());
            }
          // fall through
          case 95: break;
          case 41:
            { return new Symbol(sym.PRfalse, yyline, yycolumn,yytext());
            }
          // fall through
          case 96: break;
          case 42:
            { return new Symbol(sym.PRmatch, yyline, yycolumn,yytext());
            }
          // fall through
          case 97: break;
          case 43:
            { return new Symbol(sym.PRround, yyline, yycolumn,yytext());
            }
          // fall through
          case 98: break;
          case 44:
            { return new Symbol(sym.PRwhile, yyline, yycolumn,yytext());
            }
          // fall through
          case 99: break;
          case 45:
            { return new Symbol(sym.PRappend, yyline, yycolumn,yytext());
            }
          // fall through
          case 100: break;
          case 46:
            { return new Symbol(sym.PRdouble, yyline, yycolumn,yytext());
            }
          // fall through
          case 101: break;
          case 47:
            { return new Symbol(sym.PRlength, yyline, yycolumn,yytext());
            }
          // fall through
          case 102: break;
          case 48:
            { return new Symbol(sym.PRremove, yyline, yycolumn,yytext());
            }
          // fall through
          case 103: break;
          case 49:
            { return new Symbol(sym.PRreturn, yyline, yycolumn,yytext());
            }
          // fall through
          case 104: break;
          case 50:
            { return new Symbol(sym.PRstring, yyline, yycolumn,yytext());
            }
          // fall through
          case 105: break;
          case 51:
            { return new Symbol(sym.PRstruct, yyline, yycolumn,yytext());
            }
          // fall through
          case 106: break;
          case 52:
            { return new Symbol(sym.PRprintln, yyline, yycolumn,yytext());
            }
          // fall through
          case 107: break;
          case 53:
            { return new Symbol(sym.PRcontinue, yyline, yycolumn,yytext());
            }
          // fall through
          case 108: break;
          case 54:
            { return new Symbol(sym.PRtoString, yyline, yycolumn,yytext());
            }
          // fall through
          case 109: break;
          case 55:
            { return new Symbol(sym.PRstartWith, yyline, yycolumn,yytext());
            }
          // fall through
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
