// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Analizadores/Lexico.jflex

/*--------------------------------------------------
 ------------  1ra Area: Codigo de Usuario ---------
 ---------------------------------------------------*/

//------> Paquetes,importaciones
package Analizadores;
import Errores.ErroresL;
import proyecto.Principal;
import Objetos.Token;
import java_cup.runtime.Symbol;
import javax.swing.JOptionPane;

/*----------------------------------------------------------
  ------------  2da Area: Opciones y Declaraciones ---------
  ----------------------------------------------------------*/

@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  1,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  5,  6,  0,  0,  7,  8,  9, 10, 11, 12, 13,  0, 14, 15, 16, 
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 19, 20, 21, 22,  0, 
     0, 23, 24, 25, 26, 27, 28, 29, 30, 31,  0, 32, 33, 34, 35, 36, 
    37,  0, 38, 39, 40, 41, 42, 43,  0,  0,  0,  0,  0,  0, 44, 45, 
     0, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 
    61, 55, 62, 63, 64, 65, 66, 67, 55, 55, 55, 68, 69, 70,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\2\1\5\2\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\2\1\13\1\1\1\14"+
    "\1\15\1\16\1\17\1\20\20\2\1\21\21\22\1\23"+
    "\1\2\1\24\3\25\1\0\1\26\3\0\1\27\6\0"+
    "\1\30\4\0\1\31\16\0\5\22\1\30\4\22\1\31"+
    "\16\22\1\32\1\33\1\34\12\0\1\35\1\36\3\0"+
    "\1\37\10\0\1\40\2\0\11\22\1\35\1\36\3\22"+
    "\1\37\10\22\1\40\2\22\2\0\1\41\1\0\1\42"+
    "\3\0\1\43\1\0\1\44\1\0\1\45\11\0\1\46"+
    "\1\47\1\0\1\22\1\41\1\22\1\42\3\22\1\43"+
    "\1\22\1\44\1\22\1\45\11\22\1\46\1\47\1\22"+
    "\1\50\1\0\1\51\1\52\2\0\1\53\1\0\1\54"+
    "\3\0\1\55\4\0\1\56\1\22\1\51\1\52\2\22"+
    "\1\53\1\22\1\54\3\22\1\55\4\22\1\56\1\57"+
    "\1\0\1\60\1\61\1\0\1\62\1\63\1\0\1\64"+
    "\1\65\1\0\1\57\1\22\1\60\1\61\1\22\1\62"+
    "\1\63\1\22\1\64\1\65\1\22\1\0\1\66\2\0"+
    "\1\22\1\66\2\22\1\67\1\0\1\70\1\67\1\22"+
    "\1\70\1\0\1\22\2\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[298];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\216\0\325\0\u011c\0\107\0\u0163\0\u01aa"+
    "\0\107\0\107\0\107\0\u01f1\0\u0238\0\u027f\0\107\0\u0238"+
    "\0\107\0\107\0\u02c6\0\107\0\107\0\u030d\0\u0354\0\u039b"+
    "\0\u03e2\0\u0429\0\u0470\0\u04b7\0\u04fe\0\u0545\0\u058c\0\u05d3"+
    "\0\u061a\0\u0661\0\u06a8\0\u06ef\0\u0736\0\107\0\u077d\0\u07c4"+
    "\0\u080b\0\u0852\0\u0899\0\u08e0\0\u0927\0\u096e\0\u09b5\0\u09fc"+
    "\0\u0a43\0\u0a8a\0\u0ad1\0\u0b18\0\u0b5f\0\u0ba6\0\u0bed\0\107"+
    "\0\u0c34\0\107\0\325\0\107\0\u0c7b\0\u0cc2\0\107\0\u0d09"+
    "\0\u027f\0\u01f1\0\u027f\0\u0d50\0\u0d97\0\u0dde\0\u0e25\0\u0e6c"+
    "\0\u0eb3\0\u0efa\0\u0f41\0\u0f88\0\u0fcf\0\u1016\0\107\0\u105d"+
    "\0\u10a4\0\u10eb\0\u1132\0\u1179\0\u11c0\0\u1207\0\u124e\0\u1295"+
    "\0\u12dc\0\u1323\0\u136a\0\u13b1\0\u13f8\0\u143f\0\u1486\0\u14cd"+
    "\0\u1514\0\u155b\0\u15a2\0\u15e9\0\u1630\0\u1677\0\u16be\0\u0927"+
    "\0\u1705\0\u174c\0\u1793\0\u17da\0\u1821\0\u1868\0\u18af\0\u18f6"+
    "\0\u193d\0\u1984\0\u19cb\0\u1a12\0\u1a59\0\u1aa0\0\107\0\107"+
    "\0\107\0\u1ae7\0\u1b2e\0\u1b75\0\u1bbc\0\u1c03\0\u1c4a\0\u1c91"+
    "\0\u1cd8\0\u1d1f\0\u1d66\0\107\0\107\0\u1dad\0\u1df4\0\u1e3b"+
    "\0\107\0\u1e82\0\u1ec9\0\u1f10\0\u1f57\0\u1f9e\0\u1fe5\0\u202c"+
    "\0\u2073\0\107\0\u20ba\0\u2101\0\u2148\0\u218f\0\u21d6\0\u221d"+
    "\0\u2264\0\u22ab\0\u22f2\0\u2339\0\u2380\0\u0927\0\u0927\0\u23c7"+
    "\0\u240e\0\u2455\0\u0927\0\u249c\0\u24e3\0\u252a\0\u2571\0\u25b8"+
    "\0\u25ff\0\u2646\0\u268d\0\u0927\0\u26d4\0\u271b\0\u2762\0\u27a9"+
    "\0\107\0\u27f0\0\107\0\u2837\0\u287e\0\u28c5\0\107\0\u290c"+
    "\0\107\0\u2953\0\107\0\u299a\0\u29e1\0\u2a28\0\u2a6f\0\u2ab6"+
    "\0\u2afd\0\u2b44\0\u2b8b\0\u2bd2\0\107\0\107\0\u2c19\0\u2c60"+
    "\0\u0927\0\u2ca7\0\u0927\0\u2cee\0\u2d35\0\u2d7c\0\u0927\0\u2dc3"+
    "\0\u0927\0\u2e0a\0\u0927\0\u2e51\0\u2e98\0\u2edf\0\u2f26\0\u2f6d"+
    "\0\u2fb4\0\u2ffb\0\u3042\0\u3089\0\u0927\0\u0927\0\u30d0\0\107"+
    "\0\u3117\0\107\0\107\0\u315e\0\u31a5\0\107\0\u31ec\0\107"+
    "\0\u3233\0\u327a\0\u32c1\0\107\0\u3308\0\u334f\0\u3396\0\u33dd"+
    "\0\107\0\u3424\0\u0927\0\u0927\0\u346b\0\u34b2\0\u0927\0\u34f9"+
    "\0\u0927\0\u3540\0\u3587\0\u35ce\0\u0927\0\u3615\0\u365c\0\u36a3"+
    "\0\u36ea\0\u0927\0\107\0\u3731\0\107\0\107\0\u3778\0\107"+
    "\0\107\0\u37bf\0\107\0\107\0\u3806\0\u0927\0\u384d\0\u0927"+
    "\0\u0927\0\u3894\0\u0927\0\u0927\0\u38db\0\u0927\0\u0927\0\u3922"+
    "\0\u3969\0\107\0\u39b0\0\u39f7\0\u3a3e\0\u0927\0\u3a85\0\u3acc"+
    "\0\107\0\u3b13\0\107\0\u0927\0\u3b5a\0\u0927\0\u3ba1\0\u3be8"+
    "\0\107\0\u0927";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[298];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\2\2\1\34\1\2\1\35"+
    "\1\36\1\37\1\2\1\40\1\41\1\42\1\43\1\2"+
    "\1\44\1\45\1\46\1\2\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\2\55\1\56\2\55\1\57\1\60\1\61"+
    "\1\55\1\62\1\63\1\64\1\65\1\55\1\66\1\67"+
    "\1\70\1\71\1\72\110\0\2\3\1\0\1\3\102\0"+
    "\2\73\1\74\1\73\1\75\102\73\2\76\1\0\3\76"+
    "\1\0\100\76\10\0\1\77\76\0\2\100\1\0\6\100"+
    "\1\0\75\100\17\0\1\101\1\0\1\102\104\0\1\101"+
    "\1\0\1\20\106\0\1\103\72\0\1\104\146\0\1\105"+
    "\27\0\1\105\55\0\1\106\1\0\1\107\25\0\1\106"+
    "\1\0\1\107\46\0\1\110\5\0\1\111\20\0\1\110"+
    "\6\0\1\111\56\0\1\112\27\0\1\112\53\0\1\113"+
    "\27\0\1\113\44\0\1\114\7\0\1\115\4\0\1\116"+
    "\11\0\1\114\7\0\1\115\5\0\1\116\46\0\1\117"+
    "\6\0\1\120\17\0\1\117\7\0\1\120\46\0\1\121"+
    "\3\0\1\122\22\0\1\121\3\0\1\122\47\0\1\123"+
    "\26\0\1\123\63\0\1\124\26\0\1\124\72\0\1\125"+
    "\27\0\1\125\43\0\1\126\10\0\1\127\15\0\1\126"+
    "\11\0\1\127\62\0\1\130\27\0\1\130\52\0\1\131"+
    "\1\0\1\132\25\0\1\131\1\0\1\132\37\0\1\133"+
    "\14\0\1\134\11\0\1\133\15\0\1\134\50\0\1\135"+
    "\26\0\1\135\42\0\1\55\23\0\1\105\7\0\20\55"+
    "\1\136\6\55\24\0\1\55\22\0\1\106\1\0\1\107"+
    "\6\0\17\55\1\137\1\55\1\140\5\55\24\0\1\55"+
    "\14\0\1\110\5\0\1\111\10\0\10\55\1\141\6\55"+
    "\1\142\7\55\24\0\1\55\22\0\1\112\10\0\17\55"+
    "\1\143\7\55\24\0\1\55\17\0\1\113\13\0\14\55"+
    "\1\144\12\55\24\0\1\55\5\0\1\114\7\0\1\115"+
    "\4\0\1\116\10\0\1\55\1\145\7\55\1\146\5\55"+
    "\1\147\7\55\24\0\1\55\33\0\27\55\24\0\1\55"+
    "\12\0\1\117\6\0\1\120\11\0\6\55\1\150\7\55"+
    "\1\151\10\55\24\0\1\55\11\0\1\121\3\0\1\122"+
    "\15\0\5\55\1\152\3\55\1\153\15\55\24\0\1\55"+
    "\5\0\1\123\25\0\1\55\1\154\25\55\24\0\1\55"+
    "\11\0\1\124\21\0\5\55\1\155\21\55\24\0\1\55"+
    "\24\0\1\125\6\0\21\55\1\156\5\55\24\0\1\55"+
    "\11\0\1\126\10\0\1\127\10\0\5\55\1\157\11\55"+
    "\1\160\7\55\24\0\1\55\26\0\1\130\4\0\23\55"+
    "\1\161\3\55\24\0\1\55\22\0\1\131\1\0\1\132"+
    "\6\0\17\55\1\162\1\55\1\163\5\55\24\0\1\55"+
    "\5\0\1\133\14\0\1\134\10\0\1\55\1\164\15\55"+
    "\1\165\7\55\24\0\1\55\14\0\1\135\16\0\10\55"+
    "\1\166\16\55\110\0\1\167\3\0\1\74\104\0\2\76"+
    "\1\0\3\76\1\170\100\76\2\100\1\0\6\100\1\171"+
    "\75\100\20\172\1\0\66\172\45\0\1\173\27\0\1\173"+
    "\55\0\1\174\27\0\1\174\45\0\1\175\26\0\1\175"+
    "\53\0\1\176\26\0\1\176\73\0\1\177\27\0\1\177"+
    "\64\0\1\200\27\0\1\200\54\0\1\201\27\0\1\201"+
    "\50\0\1\202\27\0\1\202\60\0\1\203\27\0\1\203"+
    "\61\0\1\204\27\0\1\204\60\0\1\205\27\0\1\205"+
    "\51\0\1\206\27\0\1\206\62\0\1\207\27\0\1\207"+
    "\57\0\1\210\27\0\1\210\61\0\1\211\27\0\1\211"+
    "\42\0\1\212\26\0\1\212\62\0\1\213\5\0\1\214"+
    "\21\0\1\213\5\0\1\214\57\0\1\215\27\0\1\215"+
    "\34\0\1\216\16\0\1\217\7\0\1\216\17\0\1\217"+
    "\57\0\1\220\27\0\1\220\60\0\1\221\27\0\1\221"+
    "\53\0\1\222\27\0\1\222\47\0\1\223\26\0\1\223"+
    "\57\0\1\224\26\0\1\224\41\0\1\55\23\0\1\173"+
    "\7\0\20\55\1\225\6\55\24\0\1\55\22\0\1\174"+
    "\10\0\17\55\1\226\7\55\24\0\1\55\11\0\1\175"+
    "\21\0\5\55\1\227\21\55\24\0\1\55\5\0\1\176"+
    "\25\0\1\55\1\230\25\55\24\0\1\55\21\0\1\177"+
    "\11\0\16\55\1\231\10\55\24\0\1\55\27\0\1\200"+
    "\3\0\24\55\1\232\2\55\24\0\1\55\25\0\1\201"+
    "\5\0\22\55\1\233\4\55\24\0\1\55\17\0\1\202"+
    "\13\0\14\55\1\234\12\55\24\0\1\55\21\0\1\203"+
    "\11\0\16\55\1\235\10\55\24\0\1\55\24\0\1\204"+
    "\6\0\21\55\1\236\5\55\24\0\1\55\26\0\1\205"+
    "\4\0\23\55\1\237\3\55\24\0\1\55\21\0\1\206"+
    "\11\0\16\55\1\240\10\55\24\0\1\55\25\0\1\207"+
    "\5\0\22\55\1\241\4\55\24\0\1\55\26\0\1\210"+
    "\4\0\23\55\1\242\3\55\24\0\1\55\31\0\1\211"+
    "\1\0\26\55\1\243\24\0\1\55\15\0\1\212\15\0"+
    "\11\55\1\244\15\55\24\0\1\55\20\0\1\213\5\0"+
    "\1\214\4\0\15\55\1\245\5\55\1\246\3\55\24\0"+
    "\1\55\27\0\1\215\3\0\24\55\1\247\2\55\24\0"+
    "\1\55\5\0\1\216\16\0\1\217\6\0\1\55\1\250"+
    "\17\55\1\251\5\55\24\0\1\55\25\0\1\220\5\0"+
    "\22\55\1\252\4\55\24\0\1\55\27\0\1\221\3\0"+
    "\24\55\1\253\2\55\24\0\1\55\24\0\1\222\6\0"+
    "\21\55\1\254\5\55\24\0\1\55\15\0\1\223\15\0"+
    "\11\55\1\255\15\55\24\0\1\55\15\0\1\224\15\0"+
    "\11\55\1\256\15\55\3\0\5\172\1\257\101\172\33\0"+
    "\1\260\26\0\1\260\65\0\1\261\27\0\1\261\44\0"+
    "\1\262\26\0\1\262\76\0\1\263\27\0\1\263\57\0"+
    "\1\264\1\265\26\0\1\264\1\265\36\0\1\266\26\0"+
    "\1\266\62\0\1\267\26\0\1\267\73\0\1\270\27\0"+
    "\1\270\41\0\1\271\26\0\1\271\62\0\1\272\26\0"+
    "\1\272\72\0\1\273\27\0\1\273\37\0\1\274\26\0"+
    "\1\274\71\0\1\275\27\0\1\275\57\0\1\276\27\0"+
    "\1\276\63\0\1\277\27\0\1\277\50\0\1\300\27\0"+
    "\1\300\61\0\1\301\27\0\1\301\47\0\1\302\11\0"+
    "\1\303\14\0\1\302\12\0\1\303\55\0\1\304\27\0"+
    "\1\304\41\0\1\305\26\0\1\305\56\0\1\306\26\0"+
    "\1\306\66\0\1\307\27\0\1\307\36\0\1\55\11\0"+
    "\1\260\21\0\5\55\1\310\21\55\24\0\1\55\17\0"+
    "\1\261\13\0\14\55\1\311\12\55\24\0\1\55\5\0"+
    "\1\262\25\0\1\55\1\312\25\55\24\0\1\55\24\0"+
    "\1\263\6\0\21\55\1\313\5\55\24\0\1\55\25\0"+
    "\1\264\1\265\4\0\22\55\1\314\1\315\3\55\24\0"+
    "\1\55\6\0\1\266\24\0\2\55\1\316\24\55\24\0"+
    "\1\55\11\0\1\267\21\0\5\55\1\317\21\55\24\0"+
    "\1\55\25\0\1\270\5\0\22\55\1\320\4\55\24\0"+
    "\1\55\10\0\1\271\22\0\4\55\1\321\22\55\24\0"+
    "\1\55\13\0\1\272\17\0\7\55\1\322\17\55\24\0"+
    "\1\55\26\0\1\273\4\0\23\55\1\323\3\55\24\0"+
    "\1\55\7\0\1\274\23\0\3\55\1\324\23\55\24\0"+
    "\1\55\21\0\1\275\11\0\16\55\1\325\10\55\24\0"+
    "\1\55\22\0\1\276\10\0\17\55\1\326\7\55\24\0"+
    "\1\55\27\0\1\277\3\0\24\55\1\327\2\55\24\0"+
    "\1\55\21\0\1\300\11\0\16\55\1\330\10\55\24\0"+
    "\1\55\24\0\1\301\6\0\21\55\1\331\5\55\24\0"+
    "\1\55\15\0\1\302\11\0\1\303\3\0\11\55\1\332"+
    "\12\55\1\333\2\55\24\0\1\55\26\0\1\304\4\0"+
    "\23\55\1\334\3\55\24\0\1\55\11\0\1\305\21\0"+
    "\5\55\1\335\21\55\24\0\1\55\10\0\1\306\22\0"+
    "\4\55\1\336\22\55\24\0\1\55\17\0\1\307\13\0"+
    "\14\55\1\337\12\55\3\0\5\172\1\257\20\172\1\340"+
    "\60\172\43\0\1\341\27\0\1\341\53\0\1\342\27\0"+
    "\1\342\66\0\1\343\27\0\1\343\45\0\1\344\26\0"+
    "\1\344\61\0\1\345\27\0\1\345\50\0\1\346\26\0"+
    "\1\346\74\0\1\347\27\0\1\347\44\0\1\350\26\0"+
    "\1\350\71\0\1\351\27\0\1\351\60\0\1\352\27\0"+
    "\1\352\52\0\1\353\27\0\1\353\42\0\1\354\26\0"+
    "\1\354\75\0\1\355\27\0\1\355\51\0\1\356\27\0"+
    "\1\356\44\0\1\357\26\0\1\357\74\0\1\360\27\0"+
    "\1\360\43\0\1\361\26\0\1\361\45\0\1\55\21\0"+
    "\1\341\11\0\16\55\1\362\10\55\24\0\1\55\16\0"+
    "\1\342\14\0\13\55\1\363\13\55\24\0\1\55\26\0"+
    "\1\343\4\0\23\55\1\364\3\55\24\0\1\55\15\0"+
    "\1\344\15\0\11\55\1\365\15\55\24\0\1\55\17\0"+
    "\1\345\13\0\14\55\1\366\12\55\24\0\1\55\11\0"+
    "\1\346\21\0\5\55\1\367\21\55\24\0\1\55\26\0"+
    "\1\347\4\0\23\55\1\370\3\55\24\0\1\55\14\0"+
    "\1\350\16\0\10\55\1\371\16\55\24\0\1\55\26\0"+
    "\1\351\4\0\23\55\1\372\3\55\24\0\1\55\30\0"+
    "\1\352\2\0\25\55\1\373\1\55\24\0\1\55\24\0"+
    "\1\353\6\0\21\55\1\374\5\55\24\0\1\55\10\0"+
    "\1\354\22\0\4\55\1\375\22\55\24\0\1\55\26\0"+
    "\1\355\4\0\23\55\1\376\3\55\24\0\1\55\21\0"+
    "\1\356\11\0\16\55\1\377\10\55\24\0\1\55\7\0"+
    "\1\357\23\0\3\55\1\u0100\23\55\24\0\1\55\24\0"+
    "\1\360\6\0\21\55\1\u0101\5\55\24\0\1\55\11\0"+
    "\1\361\21\0\5\55\1\u0102\21\55\35\0\1\u0103\26\0"+
    "\1\u0103\70\0\1\u0104\27\0\1\u0104\46\0\1\u0105\26\0"+
    "\1\u0105\62\0\1\u0106\26\0\1\u0106\62\0\1\u0107\27\0"+
    "\1\u0107\50\0\1\u0108\26\0\1\u0108\67\0\1\u0109\27\0"+
    "\1\u0109\70\0\1\u010a\66\0\1\u010b\26\0\1\u010b\72\0"+
    "\1\u010c\27\0\1\u010c\45\0\1\u010d\26\0\1\u010d\41\0"+
    "\1\55\10\0\1\u0103\22\0\4\55\1\u010e\22\55\24\0"+
    "\1\55\21\0\1\u0104\11\0\16\55\1\u010f\10\55\24\0"+
    "\1\55\11\0\1\u0105\21\0\5\55\1\u0110\21\55\24\0"+
    "\1\55\14\0\1\u0106\16\0\10\55\1\u0111\16\55\24\0"+
    "\1\55\17\0\1\u0107\13\0\14\55\1\u0112\12\55\24\0"+
    "\1\55\11\0\1\u0108\21\0\5\55\1\u0113\21\55\24\0"+
    "\1\55\21\0\1\u0109\11\0\16\55\1\u0114\10\55\24\0"+
    "\1\55\33\0\1\u0115\26\55\24\0\1\55\13\0\1\u010b"+
    "\17\0\7\55\1\u0116\17\55\24\0\1\55\26\0\1\u010c"+
    "\4\0\23\55\1\u0117\3\55\24\0\1\55\15\0\1\u010d"+
    "\15\0\11\55\1\u0118\15\55\54\0\1\u0119\27\0\1\u0119"+
    "\50\0\1\u011a\27\0\1\u011a\66\0\1\u011b\27\0\1\u011b"+
    "\46\0\1\u011c\27\0\1\u011c\34\0\1\55\27\0\1\u0119"+
    "\3\0\24\55\1\u011d\2\55\24\0\1\55\21\0\1\u011a"+
    "\11\0\16\55\1\u011e\10\55\24\0\1\55\31\0\1\u011b"+
    "\1\0\26\55\1\u011f\24\0\1\55\21\0\1\u011c\11\0"+
    "\16\55\1\u0120\10\55\36\0\1\u0121\26\0\1\u0121\63\0"+
    "\1\u0122\26\0\1\u0122\55\0\1\u0123\26\0\1\u0123\43\0"+
    "\1\55\11\0\1\u0121\21\0\5\55\1\u0124\21\55\24\0"+
    "\1\55\15\0\1\u0122\15\0\11\55\1\u0125\15\55\24\0"+
    "\1\55\13\0\1\u0123\17\0\7\55\1\u0126\17\55\53\0"+
    "\1\u0127\27\0\1\u0127\27\0\1\55\26\0\1\u0127\4\0"+
    "\23\55\1\u0128\3\55\41\0\1\u0129\26\0\1\u0129\42\0"+
    "\1\55\14\0\1\u0129\16\0\10\55\1\u012a\16\55\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[15407];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\3\1\1\11\2\1\3\11\3\1\1\11"+
    "\1\1\2\11\1\1\2\11\20\1\1\11\21\1\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\0\1\11\3\0"+
    "\1\1\6\0\1\1\4\0\1\11\16\0\31\1\3\11"+
    "\12\0\2\11\3\0\1\11\10\0\1\11\2\0\32\1"+
    "\2\0\1\11\1\0\1\11\3\0\1\11\1\0\1\11"+
    "\1\0\1\11\11\0\2\11\1\0\30\1\1\11\1\0"+
    "\2\11\2\0\1\11\1\0\1\11\3\0\1\11\4\0"+
    "\1\11\21\1\1\11\1\0\2\11\1\0\2\11\1\0"+
    "\2\11\1\0\13\1\1\0\1\11\2\0\4\1\1\11"+
    "\1\0\1\11\3\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[298];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    //----> Codigo de usuario en sintaxis java
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { Token nuevo = new Token(yytext(), "Entero", yyline,yycolumn);
               Principal.ListaTokens.add(nuevo);
               System.out.println("Reconocio "+yytext()+" Entero"); return new Symbol(sym.entero, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 2:
            { Errores err = new ErroresL("Lexico",yytext(), yyline, yycolumn); 
                          Principal.ListaErrores.add(err);
                          err.SendError();
            }
          // fall through
          case 59: break;
          case 3:
            { /* Espacios en blanco, se ignoran */
            }
          // fall through
          case 60: break;
          case 4:
            { Token nuevo = new Token(yytext(), "NOT", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" NOT"); return new Symbol(sym.NOT, yycolumn, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 5:
            { Token nuevo = new Token(yytext(), "Porcentaje", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" Porcentaje"); return new Symbol(sym.Porcentaje, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 6:
            { Token nuevo = new Token(yytext(), "AbreParentesis", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" AbreP"); return new Symbol(sym.AbreP, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 7:
            { Token nuevo = new Token(yytext(), "CierraParentesis", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" CierraP"); return new Symbol(sym.CierraP, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 8:
            { Token nuevo = new Token(yytext(), "Asterisco", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" Asterisco"); return new Symbol(sym.Asterisco, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 9:
            { Token nuevo = new Token(yytext(), "Suma", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" Suma"); return new Symbol(sym.Suma, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 10:
            { Token nuevo = new Token(yytext(), "Resta", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" Resta"); return new Symbol(sym.Resta, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 11:
            { Token nuevo = new Token(yytext(), "Diagonal", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" Diagonal"); return new Symbol(sym.Diagonal, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 12:
            { Token nuevo = new Token(yytext(), "DosPuntos", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" DosPuntos"); return new Symbol(sym.DosPuntos, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 13:
            { Token nuevo = new Token(yytext(), "PuntoComa", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" PuntoComa"); return new Symbol(sym.PuntoComa, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 14:
            { Token nuevo = new Token(yytext(), "Menor", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" menor"); return new Symbol(sym.menor, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 15:
            { Token nuevo = new Token(yytext(), "Igual", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" Igual"); return new Symbol(sym.Igual, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 16:
            { Token nuevo = new Token(yytext(), "Mayor", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" mayor"); return new Symbol(sym.mayor, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 17:
            { Token nuevo = new Token(yytext(), "acentoPotencia", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" acentoPotencia"); return new Symbol(sym.acentoPotencia, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 18:
            { Token nuevo = new Token(yytext(), "Identificador", yyline,yycolumn);
               Principal.ListaTokens.add(nuevo);
               System.out.println("Reconocio "+yytext()+" id"); return new Symbol(sym.id, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 19:
            { Token nuevo = new Token(yytext(), "AbreCorchete", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" AbreC"); return new Symbol(sym.AbreC, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 20:
            { Token nuevo = new Token(yytext(), "CierrraCorchete", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" CierraC"); return new Symbol(sym.CierraC, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 21:
            { Token nuevo = new Token(yytext(), "Comentario Simple", yyline,yycolumn);
                        Principal.ListaTokens.add(nuevo);
                        System.out.println("Comentario: "+yytext());
            }
          // fall through
          case 78: break;
          case 22:
            { Token nuevo = new Token(yytext(), "AND", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" AND"); return new Symbol(sym.AND, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 23:
            { Token nuevo = new Token(yytext(), "Doublee", yyline,yycolumn);
               Principal.ListaTokens.add(nuevo);
               System.out.println("Reconocio "+yytext()+" doublee"); return new Symbol(sym.doublee, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 24:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" do"); return new Symbol(sym.do, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 25:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+"if"); return new Symbol(sym.if, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          case 26:
            { Token nuevo = new Token(yytext(), "OR", yyline,yycolumn);
              Principal.ListaTokens.add(nuevo);
              System.out.println("Reconocio "+yytext()+" OR"); return new Symbol(sym.OR, yycolumn, yyline, yytext());
            }
          // fall through
          case 83: break;
          case 27:
            { Token nuevo = new Token(yytext(), "Cadena", yyline,yycolumn);
               Principal.ListaTokens.add(nuevo);
               System.out.println("Reconocio "+yytext()+" cadena"); return new Symbol(sym.cadena, yycolumn, yyline, yytext());
            }
          // fall through
          case 84: break;
          case 28:
            { Token nuevo = new Token(yytext(), "character", yyline,yycolumn);
               Principal.ListaTokens.add(nuevo);
               System.out.println("Reconocio "+yytext()+" character"); return new Symbol(sym.character, yycolumn, yyline, yytext());
            }
          // fall through
          case 85: break;
          case 29:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" for"); return new Symbol(sym.for, yycolumn, yyline, yytext());
            }
          // fall through
          case 86: break;
          case 30:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" int"); return new Symbol(sym.int, yycolumn, yyline, yytext());
            }
          // fall through
          case 87: break;
          case 31:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" new"); return new Symbol(sym.new, yycolumn, yyline, yytext());
            }
          // fall through
          case 88: break;
          case 32:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" Var"); return new Symbol(sym.Var, yycolumn, yyline, yytext());
            }
          // fall through
          case 89: break;
          case 33:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" bool"); return new Symbol(sym.bool, yycolumn, yyline, yytext());
            }
          // fall through
          case 90: break;
          case 34:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" char"); return new Symbol(sym.char, yycolumn, yyline, yytext());
            }
          // fall through
          case 91: break;
          case 35:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+"else"); return new Symbol(sym.else, yycolumn, yyline, yytext());
            }
          // fall through
          case 92: break;
          case 36:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" find"); return new Symbol(sym.find, yycolumn, yyline, yytext());
            }
          // fall through
          case 93: break;
          case 37:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" list"); return new Symbol(sym.list, yycolumn, yyline, yytext());
            }
          // fall through
          case 94: break;
          case 38:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" true"); return new Symbol(sym.true, yycolumn, yyline, yytext());
            }
          // fall through
          case 95: break;
          case 39:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" void"); return new Symbol(sym.void, yycolumn, yyline, yytext());
            }
          // fall through
          case 96: break;
          case 40:
            { Token nuevo = new Token(yytext(), "Comentario Multi", yyline,yycolumn);
                        Principal.ListaTokens.add(nuevo);
                        System.out.println("Comentario: "+yytext());
            }
          // fall through
          case 97: break;
          case 41:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" break"); return new Symbol(sym.break, yycolumn, yyline, yytext());
            }
          // fall through
          case 98: break;
          case 42:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" Const"); return new Symbol(sym.const, yycolumn, yyline, yytext());
            }
          // fall through
          case 99: break;
          case 43:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" false"); return new Symbol(sym.false, yycolumn, yyline, yytext());
            }
          // fall through
          case 100: break;
          case 44:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" match"); return new Symbol(sym.match, yycolumn, yyline, yytext());
            }
          // fall through
          case 101: break;
          case 45:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" round"); return new Symbol(sym.round, yycolumn, yyline, yytext());
            }
          // fall through
          case 102: break;
          case 46:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" while"); return new Symbol(sym.while, yycolumn, yyline, yytext());
            }
          // fall through
          case 103: break;
          case 47:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" append"); return new Symbol(sym.append, yycolumn, yyline, yytext());
            }
          // fall through
          case 104: break;
          case 48:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" double"); return new Symbol(sym.double, yycolumn, yyline, yytext());
            }
          // fall through
          case 105: break;
          case 49:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" length"); return new Symbol(sym.length, yycolumn, yyline, yytext());
            }
          // fall through
          case 106: break;
          case 50:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" remove"); return new Symbol(sym.remove, yycolumn, yyline, yytext());
            }
          // fall through
          case 107: break;
          case 51:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" return"); return new Symbol(sym.return, yycolumn, yyline, yytext());
            }
          // fall through
          case 108: break;
          case 52:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" string"); return new Symbol(sym.string, yycolumn, yyline, yytext());
            }
          // fall through
          case 109: break;
          case 53:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" struct"); return new Symbol(sym.struct, yycolumn, yyline, yytext());
            }
          // fall through
          case 110: break;
          case 54:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" println"); return new Symbol(sym.println, yycolumn, yyline, yytext());
            }
          // fall through
          case 111: break;
          case 55:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" continue"); return new Symbol(sym.continue, yycolumn, yyline, yytext());
            }
          // fall through
          case 112: break;
          case 56:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" toString"); return new Symbol(sym.toString, yycolumn, yyline, yytext());
            }
          // fall through
          case 113: break;
          case 57:
            { Token nuevo = new Token(yytext(), "Palabra Reservada", yyline,yycolumn);
                Principal.ListaTokens.add(nuevo);
                System.out.println("Reconocio "+yytext()+" startWith"); return new Symbol(sym.startWith, yycolumn, yyline, yytext());
            }
          // fall through
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
