

package Analizadores;

//importaciones si fuese necesario

import java_cup.runtime.Symbol;
import java.util.LinkedList;

import proyecto.Principal;
import Errores.Errores;
import Objetos.*;
import Expresiones.*;
import Instruccions.*;


//codigo de la clase parser
parser code 
{:
    
    scanner s;
    parser(scanner s){this.s = s;}

    public LinkedList<Errores> listaErrores = new LinkedList<>();
    
    public void syntax_error(Symbol s){
        listaErrores.add(new Errores("SINTACTICO RECUPERABLE",
                        "No se esperaba el componente "+s.value,
                        s.left,
                        s.right));
    }

    public void unrecovered_syntax_error (Symbol s){
        listaErrores.add(new Errores("SINTACTICO NO RECUPERABLE",
                        "No se esperaba el componente "+s.value,
                        s.left,
                        s.right));
    }
:}

action code
{:
:}

terminal DosPuntos, Igual, menor, mayor, Resta, PuntoComa, AbreC, CierraC, acentoPotencia, Porcentaje;
terminal AbreP, CierraP, SYMAND, SYMOR, SYMNOT, Diagonal, Suma, Asterisco;
terminal potencia, negacionUnario, igualacion, Diferencia, menorIgual, mayorIgual;
terminal PRvar, PRconst, PRint, PRdouble, PRbool, PRtrue, PRfalse, PRchar, PRstring, PRif, PRelse, PRmatch, PRwhile, PRfor, PRdo, PRbreak; 
terminal PRcontinue, PRreturn, PRnew, PRlist, PRappend, PRremove, PRstruct, PRvoid, PRprintln, PRround, PRlength, PRtoString, PRfind, PRstartWith;
terminal cadena, doublee, ident, character, entero;

nonterminal LinkedList<Instrucciones> INICIO, INSTRUCCIONES;
nonterminal Instrucciones INSTRUCCION;
nonterminal Instrucciones IMPRESION, DECLARACION, ASIGNACION;
nonterminal Instrucciones BREAK;
nonterminal Tipo TIPOS;
nonterminal Instrucciones EXPRESION;

start with INICIO;

INICIO ::= INSTRUCCIONES:a      {:   RESULT = a;   :}
;

INSTRUCCIONES ::= INSTRUCCIONES:a INSTRUCCION:b     {: RESULT = a; RESULT.add(b); :}
                | INSTRUCCION:a                   {: RESULT = new LinkedList<>(); RESULT.add(a); :}
;

INSTRUCCION ::= IMPRESION: a        {:   RESULT=a;   :}
              | DECLARACION:a       {:   RESULT=a;   :}
              | ASIGNACION:a        {:   RESULT=a;   :}
              | BREAK:a            {:   RESULT=a;   :}
              | error PuntoComa
;

IMPRESION ::= PRprintln AbreP EXPRESION:a CierraP PuntoComa      {:   RESULT = new Println(a, aleft, aright);   :}
;
                                                                                   
DECLARACION ::= PRvar ident:b DosPuntos TIPOS:a Igual EXPRESION:c PuntoComa    {:  SimboloTabla nuevo = new SimboloTabla((String) b, "VAR" ,c , "FULL", aleft, aright);
                                                                                    Principal.ListaSimbolos.add(nuevo); RESULT = new Declaracion("var",(String) b, c, a, aleft, aright);   :}
              | PRvar ident:b DosPuntos TIPOS:a PuntoComa                      {:  SimboloTabla nuevo = new SimboloTabla((String) b, "VAR" ,null , "FULL", aleft, aright);
                                                                                    Principal.ListaSimbolos.add(nuevo);RESULT = new Declaracion("var",(String) b, null, a, aleft, aright);   :}
              | PRconst ident:b DosPuntos TIPOS:a Igual EXPRESION:c PuntoComa    {:   SimboloTabla nuevo = new SimboloTabla((String) b, "CONST" ,c , "FULL", aleft, aright);
                                                                                    Principal.ListaSimbolos.add(nuevo);RESULT = new Declaracion("const",(String) b, c, a, aleft, aright);   :}
              | PRconst ident:b DosPuntos TIPOS:a PuntoComa                      {:   SimboloTabla nuevo = new SimboloTabla((String) b, "CONST" ,null , "FULL", aleft, aright);
                                                                                    Principal.ListaSimbolos.add(nuevo);RESULT = new Declaracion("const",(String) b, null, a, aleft, aright);   :}
;

ASIGNACION ::= ident:a Igual EXPRESION:b PuntoComa  {:   RESULT = new Asignacion((String) a, b, aleft, aright);  :}
;

TIPOS ::= PRint       {:   RESULT=new Tipo(tipoDato.ENTERO);   :}
        | PRdouble    {:   RESULT=new Tipo(tipoDato.DECIMAL);   :}
        | PRstring    {:   RESULT=new Tipo(tipoDato.CADENA);   :}
        | PRbool      {:   RESULT=new Tipo(tipoDato.BOOLEANO);   :}
        | PRchar      {:   RESULT=new Tipo(tipoDato.CARACTER);   :}
;

EXPRESION ::= entero:a                              {:   RESULT = new Nativo(Integer.parseInt((String) a), new Tipo(tipoDato.ENTERO), aleft, aright );   :}
            | doublee:a                             {:   RESULT = new Nativo(new Double((double) a), new Tipo(tipoDato.DECIMAL), aleft, aright );   :}
            | cadena:a                              {:   RESULT = new Nativo(a, new Tipo(tipoDato.CADENA), aleft, aright );   :}
            | PRtrue:a                              {:   RESULT = new Nativo(true, new Tipo(tipoDato.BOOLEANO), aleft, aright );   :}
            | PRfalse:a                             {:   RESULT = new Nativo(false, new Tipo(tipoDato.BOOLEANO), aleft, aright );    :}
            | ident:a                               {:   RESULT = new AccesoVAR((String) a, aleft, aright);   :}
            | AbreP EXPRESION:a CierraP             {:   RESULT = a;   :}
;