

package Analizadores;

//importaciones si fuese necesario

import java_cup.runtime.Symbol;
import java.util.LinkedList;
import proyecto.Principal;

import Errores.Errores;

import Objetos.Simbolo;
import Objetos.Instrucciones;


//codigo de la clase parser
parser code 
{:
    public void syntax_error(Symbol s){
        System.out.println("Error Sintactico Recuperable");
        Errores nuevo = new Errores("Error Sintactico Recuperable", s.value.toString(), s.right+1, s.left+1);
        Principal.ListaErrores.add(nuevo);
    }

    public void unrecovered_syntax_error(Symbol s){
        System.out.println("Error Sintactico no recuperable");
        Errores nuevo = new Errores("Error Sintactico no recuperable", s.value.toString(), s.right+1, s.left+1);
        Principal.ListaErrores.add(nuevo);
    }
:}

action code
{:
    String codigoUsr="";
:}

terminal DosPuntos, Igual, menor, mayor, Resta, PuntoComa, AbreC, CierraC, acentoPotencia, Porcentaje, AbreP, CierraP, SymAND, SymOR, SymNOT, Diagonal, Suma, Asterisco;
terminal PRvar, PRconst, PRint, PRdouble, PRbool, PRtrue, PRfalse, PRchar, PRstring, PRif, PRelse, PRmatch, PRwhile, PRfor, PRdo, PRbreak; 
terminal PRcontinue, PRreturn, PRnew, PRlist, PRappend, PRremove, PRstruct, PRvoid, PRprintln, PRround, PRlength, PRtoString, PRfind, PRstartWith;
terminal cadena, doublee, id, character, entero;

nonterminal String INICIO;
nonterminal INSTRUCCIONES, INSTRUCCION;
nonterminal IMPRESION, DECLARACION, ASIGNACION;
nonterminal DECLARACIONINT, DECLARACIONDOU, DECLARACIONBOOL, DECLARACIONCHAR, DECLARACIONSTRING;


start with INICIO;

INICIO ::= INSTRUCCIONES
{:RESULT = codigoUsr; :} 
;

INSTRUCCIONES ::= INSTRUCCION:a INSTRUCCIONES     {: RESULT = a; :}
                | INSTRUCCION:a                     {: RESULT = a; :}
;

INSTRUCCION ::= IMPRESION: a        {:   RESULT=a;   :}
              | DECLARACION:a       {:   RESULT=a;   :}
              | ASIGNACION:a        {:   RESULT=a;   :}
;

DECLARACION ::= DECLARACIONINT:a    {:   RESULT=a;   :}
              | DECLARACIONDOU:a    {:   RESULT=a;   :}
              | DECLARACIONBOOL:a   {:   RESULT=a;   :}
              | DECLARACIONCHAR:a   {:   RESULT=a;   :}
              | DECLARACIONSTRING:a {:   RESULT=a;   :}
;

DECLARACIONINT ::= PRvar id:a DosPuntos PRint:b Igual entero:c PuntoComa
{: System.out.println("la variable" + a + "es: " + c); :}
;