/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import Analizadores.parser;
import Analizadores.scanner;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import Errores.Errores;
import Objetos.*;
import Instruccions.*;
import java.awt.Desktop;
import java.io.PrintWriter;
import java.util.LinkedList;

/**
 *
 * @author jeach
 */
public class Principal extends javax.swing.JFrame {
    
    public static LinkedList<Errores> listaErrores = new LinkedList<>();
    public static ArrayList<SimboloTabla> ListaSimbolos;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelPestañas = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaNueva = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        ArchivoNuevo = new javax.swing.JMenuItem();
        ArchivoAbrir = new javax.swing.JMenuItem();
        ArchivoGuardar = new javax.swing.JMenuItem();
        MenuPestañas = new javax.swing.JMenu();
        MenuEjecutar = new javax.swing.JMenu();
        BotonEjecutar = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        ReporteErrores = new javax.swing.JMenuItem();
        ReporteAST = new javax.swing.JMenuItem();
        ReporteTablaSimbolo = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Entrada");

        TextAreaNueva.setColumns(20);
        TextAreaNueva.setRows(5);
        jScrollPane2.setViewportView(TextAreaNueva);

        PanelPestañas.addTab("Nuevo", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPestañas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 626, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Consola");

        Consola.setEditable(false);
        Consola.setColumns(20);
        Consola.setRows(5);
        Consola.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        jScrollPane3.setViewportView(Consola);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 609, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        MenuArchivo.setText("Archivo");

        ArchivoNuevo.setText("Nuevo");
        ArchivoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoNuevoActionPerformed(evt);
            }
        });
        MenuArchivo.add(ArchivoNuevo);

        ArchivoAbrir.setText("Abrir");
        ArchivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoAbrirActionPerformed(evt);
            }
        });
        MenuArchivo.add(ArchivoAbrir);

        ArchivoGuardar.setText("Guardar");
        ArchivoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoGuardarActionPerformed(evt);
            }
        });
        MenuArchivo.add(ArchivoGuardar);

        jMenuBar2.add(MenuArchivo);

        MenuPestañas.setText("Pestañas");
        jMenuBar2.add(MenuPestañas);

        MenuEjecutar.setText("Ejecutar");
        MenuEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEjecutarActionPerformed(evt);
            }
        });

        BotonEjecutar.setText("EJECUTAR");
        BotonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEjecutarActionPerformed(evt);
            }
        });
        MenuEjecutar.add(BotonEjecutar);

        jMenuBar2.add(MenuEjecutar);

        MenuReportes.setText("Reportes");

        ReporteErrores.setText("Errores");
        ReporteErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteErroresActionPerformed(evt);
            }
        });
        MenuReportes.add(ReporteErrores);

        ReporteAST.setText("AST");
        MenuReportes.add(ReporteAST);

        ReporteTablaSimbolo.setText("Tabla Simbolos");
        ReporteTablaSimbolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteTablaSimboloActionPerformed(evt);
            }
        });
        MenuReportes.add(ReporteTablaSimbolo);

        jMenuBar2.add(MenuReportes);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton de Nuevo Archivo
    private void ArchivoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoNuevoActionPerformed
        JTextArea textArea = new JTextArea();
        JScrollPane scrollPane = new JScrollPane(textArea);
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify file name and location");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int userSelection = fileChooser.showSaveDialog(this);
        
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToCreate = fileChooser.getSelectedFile();
            String path = fileToCreate.getAbsolutePath();
            if (!path.endsWith(".jc")) {
                path += ".jc";
            }
            try {
                if (!new File(path).createNewFile()) {
                    JOptionPane.showMessageDialog(this, "File could not be created", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "File created successfully: " + fileToCreate.getAbsolutePath(), "Success", JOptionPane.INFORMATION_MESSAGE);
                    PanelPestañas.addTab(fileToCreate.getName() , scrollPane);
          
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ArchivoNuevoActionPerformed
    //Para el reporte de Errores
    private void ReporteErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteErroresActionPerformed
        try {
            generarReporteErrores();
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ReporteErroresActionPerformed
    
    public static void generarReporteErrores() throws IOException{
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            String path = "ReporteErrores.html";
            fichero = new FileWriter(path);
            pw = new PrintWriter(fichero);
            //comenzamos a escribir el html
            pw.println("<html>");
            pw.println("<head><title>REPORTE DE ERRORES"
                    + "</title></head>");
            pw.println("<body>");
            pw.println("<div align=\"center\">");
            pw.println("<h1>REPORTE DE ERRORES</h1>");
            pw.println("<br></br>");
            pw.println("<table border=1>");
            pw.println("<tr>");
            pw.println("<td>NO.</td>");
            pw.println("<td>TIPO</td>");
            pw.println("<td>DESCRIPCION</td>");
            pw.println("<td>FILA</td>");
            pw.println("<td>COLUMNA</td>");
            pw.println("</tr>");
            for (int i = 0; i < listaErrores.size(); i++) {
                pw.println("<tr>");
                pw.println("<td>" + i + "</td>");
                pw.println("<td>" + listaErrores.get(i).getTipo() + "</td>");
                pw.println("<td>" + listaErrores.get(i).getCaracter() + "</td>");
                pw.println("<td>" + listaErrores.get(i).getFila() + "</td>");
                pw.println("<td>" + listaErrores.get(i).getColumna() + "</td>");
                pw.println("</tr>");
            }
            pw.println("</table>");
            pw.println("</div");
            pw.println("</body>");
            pw.println("</html>");
            Desktop.getDesktop().open(new File(path));
        } catch (Exception e) {
        } finally {
            if (null != fichero) {
                fichero.close();
            }
        }
    }
    
    public static void generarReporteSimbolos() throws IOException{
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            String path = "TablaSimbolos.html";
            fichero = new FileWriter(path);
            pw = new PrintWriter(fichero);
            //comenzamos a escribir el html
            pw.println("<html>");
            pw.println("<head><title>TABLA DE SIMBOLOS"
                    + "</title></head>");
            pw.println("<body>");
            pw.println("<div align=\"center\">");
            pw.println("<h1>TABLA DE SIMBOLOS</h1>");
            pw.println("<br></br>");
            pw.println("<table border=1>");
            pw.println("<tr>");
            pw.println("<td>NO.</td>");
            pw.println("<td>NOMBRE_ID</td>");
            pw.println("<td>TIPO</td>");
            pw.println("<td>VALOR</td>");
            pw.println("<td>ENTORNO</td>");
            pw.println("<td>FILA</td>");
            pw.println("<td>COLUMNA</td>");
            pw.println("</tr>");
            for (int i = 0; i < ListaSimbolos.size(); i++) {
                pw.println("<tr>");
                pw.println("<td>" + i + "</td>");
                pw.println("<td>" + ListaSimbolos.get(i).getIdentificador() + "</td>");
                pw.println("<td>" + ListaSimbolos.get(i).getTipo() + "</td>");
                pw.println("<td>" + ListaSimbolos.get(i).getValor() + "</td>");
                pw.println("<td>" + ListaSimbolos.get(i).getEntorno() + "</td>");
                pw.println("<td>" + ListaSimbolos.get(i).getFila() + "</td>");
                pw.println("<td>" + ListaSimbolos.get(i).getColumna() + "</td>");
                pw.println("</tr>");
            }
            pw.println("</table>");
            pw.println("</div");
            pw.println("</body>");
            pw.println("</html>");
            Desktop.getDesktop().open(new File(path));
        } catch (Exception e) {
        } finally {
            if (null != fichero) {
                fichero.close();
            }
        }
        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    //Boton para Guardar Arhivo
    private void ArchivoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoGuardarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save file");
        fileChooser.setFileFilter(new FileNameExtensionFilter("JC(.jc)", "jc"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String fileName = fileToSave.getAbsolutePath();

            if (!fileName.endsWith(".jc")) {
                fileName += ".jc";
            }

            try (FileWriter fileWriter = new FileWriter(fileName)) {
                Component aux = PanelPestañas.getSelectedComponent();
                if (aux instanceof JScrollPane) {
                    // Get the JTextArea inside the JScrollPane
                    JTextArea selectedTextArea = (JTextArea) ((JScrollPane) aux).getViewport().getView();
                    fileWriter.write(selectedTextArea.getText());
                    PanelPestañas.remove(aux);
                }
                JOptionPane.showMessageDialog(this, "File saved successfully: " + fileName, "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ArchivoGuardarActionPerformed
    
    //Boton para Abrir un Arhivo
    private void ArchivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoAbrirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JC(.jc)", "jc");
        fileChooser.setFileFilter(filtroImagen);
        fileChooser.setDialogTitle("Specify a file");
        fileChooser.showSaveDialog(null);

        try {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            File f = fileChooser.getSelectedFile();
            BufferedReader bf = new BufferedReader(new FileReader(f));
            String name = f.getName();
            if (name.endsWith(".jc")) {
                name = name.substring(0, name.length()-3);
            }
            
            String line;
            StringBuilder text = new StringBuilder();
            while ((line = bf.readLine()) != null) {
                text.append(line).append("\n");
            }
            JTextArea textArea = new JTextArea(text.toString());
            JScrollPane scrollPane = new JScrollPane(textArea);
            PanelPestañas.addTab(name, scrollPane);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_ArchivoAbrirActionPerformed

    private void MenuEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEjecutarActionPerformed
        
       
    }//GEN-LAST:event_MenuEjecutarActionPerformed

    private void BotonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEjecutarActionPerformed
        try{
            Component selectedComponent = PanelPestañas.getSelectedComponent();
            ListaSimbolos = new ArrayList<>();
            // Check if the selected component is a JPanel
            if (selectedComponent instanceof JScrollPane) {
                JTextArea selectedTextArea = (JTextArea) ((JScrollPane) selectedComponent).getViewport().getView();
                
                scanner sintac = new scanner(new BufferedReader(new StringReader(selectedTextArea.getText())));
                parser par = new parser(sintac);
                var result = par.parse();  
                
                var ast = new Arbol((LinkedList<Instrucciones>) result.value);
                var tabla = new tablaSimbolos();
                tabla.setNombre("GLOBAL");
                ast.setConsola("");
                
                listaErrores.addAll(sintac.listaErrores);
                listaErrores.addAll(par.listaErrores);
                
                for (var a : ast.getInstrucciones()) {
                if (a == null) {
                    continue;
                    }

                var res = a.interpretar(ast, tabla);
                if (res instanceof Errores) {
                    listaErrores.add((Errores) res);
                    }
                }
                Consola.setText(ast.getConsola());
                for (var i : listaErrores) {
                System.out.println(i);
                }
                
                
            }
  
        }catch(Exception e){
            System.out.println("Error en parser");
        }
    }//GEN-LAST:event_BotonEjecutarActionPerformed

    private void ReporteTablaSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteTablaSimboloActionPerformed
        try {
            generarReporteSimbolos();
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ReporteTablaSimboloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ArchivoAbrir;
    private javax.swing.JMenuItem ArchivoGuardar;
    private javax.swing.JMenuItem ArchivoNuevo;
    private javax.swing.JMenuItem BotonEjecutar;
    private javax.swing.JTextArea Consola;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuEjecutar;
    private javax.swing.JMenu MenuPestañas;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JTabbedPane PanelPestañas;
    private javax.swing.JMenuItem ReporteAST;
    private javax.swing.JMenuItem ReporteErrores;
    private javax.swing.JMenuItem ReporteTablaSimbolo;
    private javax.swing.JTextArea TextAreaNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
